blank_issues_enabled: false
contact_links:
  - name: 🗨 Discord
    url: https://discord.gg/znAv4yVVHq
    about: Have something unspecific to SweatControl in mind? Join the LYGHTNING Server and ask in the general chat!