blank_issues_enabled: false
contact_links:
  - name: 🗨 Discord
    url: https://discord.gg/znAv4yVVHq
    about: Hast Du sonstige Fragen? Trete unserem Server bei und frage @aeycen in einer Privatnachricht!